missing import of datetime
option --add-timestamp causing error:

Traceback (most recent call last):
  File "/home/andrzej/PycharmProjects/offline_riskzones/venv/bin/ogr2osm", line 11, in <module>
    load_entry_point('ogr2osm', 'console_scripts', 'ogr2osm')()
  File "/home/andrzej/PycharmProjects/offline_riskzones/venv/src/ogr2osm/ogr2osm.py", line 781, in main
    output()
  File "/home/andrzej/PycharmProjects/offline_riskzones/venv/src/ogr2osm/ogr2osm.py", line 505, in output
    attributes.update({'timestamp':datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ')})
NameError: name 'datetime' is not defined